sudo: required

services:
  - docker

before_install:
  - docker pull asciidoctor/docker-asciidoctor:latest

script:
  - docker run -i -v ${PWD}:/documents/ -t --name thebeambook asciidoctor/docker-asciidoctor bash -c "apk add --no-cache git rsync erlang && make"

after_error:
  - docker logs thebeambook

after_failure:
  - docker logs thebeambook

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: TvdImheIruh2daknIMPJEw0X/IOxiFCmcx12HX4xrW4J3/p8vNYMFWUtf5CBbjaNjAfz7QKP15hcRpLQGJb6llF20Kqb2NDZZEDa+2u2wonTAMlucenmrorjK8p7ZEZ/m69VROLv9Co+C+gNYVLjiDtk2y8l99/4Onn6Z+HDOSUWFklp7K4x1iiwJB3MaXu42UQZtAavv3RXspKPqs+WcrtMs1kCwaVnY1AhcUnT8A08AtZ40sKO+g8+bx/ee4DqhfhSuNZOliWNBX0Q5CAyHYd7aXExLlKWO8yFaYDdASOSg0S793FdmOyaZOeT1hpUYjiJpscujWqiNOxPqS1AT0826kgbNcuT/ERI99R2n4jgwNto37FFhQpA/dN4ylTZB5BldH034JFRcTUmCTsqX9QF+NndvgZVgyKRxXQkdPj+2IyHRXA+Ranv+MEaye1T8NKi6akgoW512UhyWAVna89WGlCIYcfI+jL4ouh9d2nL6e+e5EZvFwPAqkUCrMpDRly218g4t2I/PtxVU5FI1dAHnTts6PdtTTqfZnpIOTdt/KUs1d7Oc5b/eYPFuK60Vdmi4gXGRCUh5LS/tNgsX1LZV0Zoqw5yQvTpkBfjkeM553ZV8HA4Q67Y9PO01uP/p6DDaT0SsGJD3cly1DbMTBr5aLtmUI+VTvo72PAq16M=
    file: beam-book.pdf
    on:
      repo: happi/theBeamBook
      branch: master
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token:
      secure: TvdImheIruh2daknIMPJEw0X/IOxiFCmcx12HX4xrW4J3/p8vNYMFWUtf5CBbjaNjAfz7QKP15hcRpLQGJb6llF20Kqb2NDZZEDa+2u2wonTAMlucenmrorjK8p7ZEZ/m69VROLv9Co+C+gNYVLjiDtk2y8l99/4Onn6Z+HDOSUWFklp7K4x1iiwJB3MaXu42UQZtAavv3RXspKPqs+WcrtMs1kCwaVnY1AhcUnT8A08AtZ40sKO+g8+bx/ee4DqhfhSuNZOliWNBX0Q5CAyHYd7aXExLlKWO8yFaYDdASOSg0S793FdmOyaZOeT1hpUYjiJpscujWqiNOxPqS1AT0826kgbNcuT/ERI99R2n4jgwNto37FFhQpA/dN4ylTZB5BldH034JFRcTUmCTsqX9QF+NndvgZVgyKRxXQkdPj+2IyHRXA+Ranv+MEaye1T8NKi6akgoW512UhyWAVna89WGlCIYcfI+jL4ouh9d2nL6e+e5EZvFwPAqkUCrMpDRly218g4t2I/PtxVU5FI1dAHnTts6PdtTTqfZnpIOTdt/KUs1d7Oc5b/eYPFuK60Vdmi4gXGRCUh5LS/tNgsX1LZV0Zoqw5yQvTpkBfjkeM553ZV8HA4Q67Y9PO01uP/p6DDaT0SsGJD3cly1DbMTBr5aLtmUI+VTvo72PAq16M=
    local_dir: site
    on:
      repo: happi/theBeamBook
      branch: master
      tags: true
